[package]
name = "websocket-service"
version = "1.5.4"
authors = ["–êleksej Petrov <apetrov@wavesplatform.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
envy = "0.4"
futures = "0.3"
futures-util = "0.3"
redis = "0.20.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "sync", "signal"] }
warp = "0.3"
wavesexchange_log = { git = "https://github.com/waves-exchange/wavesexchange-rs", tag = "wavesexchange_log/0.5.0" }
wavesexchange_warp = { git = "https://github.com/waves-exchange/wavesexchange-rs", tag = "wavesexchange_warp/0.12.2" }
bb8 = "0.7"
bb8-redis = "0.9"
url = "2.2.0"
wavesexchange_topic = { git = "https://github.com/waves-exchange/wavesexchange-rs", tag = "wavesexchange_topic/0.2.1" }
prometheus = "0.12"
lazy_static = "1.4"
slog = { version = "2.5", features = ["max_level_trace", "release_max_level_debug"] }

# Tracing
tracing = { version = "0.1", features = ["log-always"] }
tracing-opentelemetry = "0.12"
tracing-subscriber = { version = "0.2", default-features = false, features = ["env-filter", "registry", "fmt"] }
tracing-futures = "0.2"
opentelemetry = { version = "0.13", features = ["rt-tokio"] }
opentelemetry-jaeger = "0.12"

[dev-dependencies]
anyhow = "1.0"

[[bin]]
name = "service"
path = "src/main.rs"
