[package]
name = "websocket-service"
version = "1.2.1"
authors = ["–êleksej Petrov <apetrov@wavesplatform.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
envy = "0.4"
futures = "0.3"
futures-util = "0.3"
redis = "0.18.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "0.2", features = ["macros", "rt-core", "rt-threaded", "sync", "signal", "blocking"] }
warp = "0.2"
wavesexchange_log = { git = "https://github.com/waves-exchange/wavesexchange-rs", tag = "wavesexchange_log/0.1.0" }
wavesexchange_warp = { git = "https://github.com/waves-exchange/wavesexchange-rs", tag = "wavesexchange_warp/0.5.0" }
bb8 = "0.5.1"
bb8-redis = "0.6"
url = "2.2.0"
wavesexchange_topic = { git = "https://github.com/waves-exchange/wavesexchange-rs", tag = "wavesexchange_topic/0.1.0" }

[[bin]]
name = "service"
path = "src/main.rs"
